[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
scarcity_exchange = "CJHWP9ed1BzWVQhUeJPQ9jJb4YcVWiFNpQcG7mPEGk86"

[programs.devnet]
scarcity_exchange = "CJHWP9ed1BzWVQhUeJPQ9jJb4YcVWiFNpQcG7mPEGk86"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/scarcity-exchange"]
